### ISSUE TITLE
Placing an order with insufficient balance needs to show Error

### ISSUE THREAD

**Issue by BKdilse** [The-GNTL-Project/Exchange#34] opened 2021-04-26 07:15 UTC
Currently, there is no feedback, and the order fields just go blank once submitted.

**Comment by tylerjohneddy** [comment] 2021-04-26 13:34
agreed, additionally could we prevent the trade being submitted using JS ? simular to how other exchanges show it

**Comment by tylerjohneddy** [comment] 2021-04-27 10:39
duplicate of #29

**Closed by tylerjohneddy** 2021-04-27 10:39 UTC
Labels: duplicate
