### ISSUE TITLE
Clicking on one of the buy or sell orders should the pre-populate the 'buy now' or 'sell now' fields

### ISSUE THREAD

**Issue by baldtrooper** [The-GNTL-Project/Exchange#44] opened 2021-04-28 10:51 UTC
I thought I had logged this or someone else did but now i cant see it, i just checked and it doesn't do it so I've re-opened it. Put it down as an enhancement

**Comment by BKdilse** [comment] 2021-04-28 11:15
Duplicate of [#36]

**Closed by BKdilse** 2021-04-28 11:15 UTC
